### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by revington** [armon/bloomd#36]
Is this project abandoned? I'm asking this question because the build for the master branch has been broken for almost a year. I think this is a really useful project and I want to use it in a production environment.

**Comment by armon** [comment]
@revington The project is not abandoned, and works fine. Travis is particularly fickle with the bloomd tests and they tend to timeout. I'll hit re-run but should be good to go!

**Comment by armon** [comment]
I'll close this, but please reopen if you have an issue.

**Comment by armon** [comment]
@revington Build is green now!

**Comment by revington** [comment]
Thank you!
