### ISSUE TITLE
can not build on ARM CPU

### ISSUE THREAD

**Issue by vlike** [armon/bloomd#37]
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o src/bloomd/art.o -c -std=c99 -D_GNU_SOURCE -Wall -Wextra -Werror -O2 -pthread -Isrc/bloomd/ -Ideps/inih/ -Ideps/libev/ -Isrc/libbloom/ src/bloomd/art.c
src/bloomd/art.c:5:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
scons: *** [src/bloomd/art.o] Error 1
scons: building terminated because of errors.

can somebody tell how to fix it?

**Comment by armon** [comment]
@vlike The radix tree depends on a pretty specific x86 instruction, it could be ifdef and replaced with a linear scan on ARM, please open a PR if you get a chance!
