### ISSUE TITLE
Question: cuckoo filter

### ISSUE THREAD

**Issue by l15k4** [armon/bloomd#45]
Hi,

I was wondering, using both bloom and cuckoo filters with different hash functions and thus reducing the collision rate, it would be highly unlikely that both filters could make false positive for the same element, also the overall size/memory footprint and performance would be better.

Ie. using both bloom and cuckoo filters with high FPP (0.01) would lead to wayyy lower collision rate than using only Bloom or Cuckoo filter with low FPP (0.00001) and it would be faster and smaller.

Have you considered adding support for https://github.com/efficient/cuckoofilter ?

**Comment by armon** [comment]
@l15k4 It definitely looks interesting, I haven't considered it, as the algorithm was published after bloomd was written! It would be an neat extension, unfortunately I don't have time for that large of a change as the project is mostly in maintenance mode now. Would be open to a PR potentially, and happy to talk through a design doc!
